config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index', as: 'admin'
  get 'contact' => 'messages#new', as: 'blog_contact'
  get 'about' => 'blog#about', as: 'blog_about'
  get 'article/show/:id' => 'blog#article', as: 'blog_article'
  
  scope :admin do 
    resources :articles do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  resources :messages

  devise_for :users
  root 'blog#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, :text, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  validates :body, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :sender, :title, :body, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  before_create :set_role, unless: :role
  validates :name, presence: true
  
  has_many :comments
  has_many :articles

  def role_symbols
    [role.title.to_sym]
  end

  def set_role
    role_user = Role.find_by(title: 'user')
    unless role_user
      role_user = Role.create(title: 'user')
    end
    self.role = role_user
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  filter_access_to :all
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_filter { |c| Authorization.current_user = c.current_user }
  protect_from_forgery with: :exception

  protected
    def permission_denied
      flash[:error] = "Sorry, you are not allowed to access that page."
      redirect_to root_url
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :role_id << :name
      devise_parameter_sanitizer.for(:account_update) << :role_id << :name
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  filter_resource_access

  def index
    @articles = Article.page(params[:page]).per(5)

    respond_to do |format|
      format.html
      format.js {}
    end
  end
  
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
    @author = params[:author]
  end

  def edit
    @article = Article.find(params[:id])
    @author = params[:author]
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id if current_user
    @author = params[:author]

    if @article.save
      if @author == "true"
        redirect_to root_path
      else
        redirect_to articles_path
      end
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    @author = params[:author]

    if @article.update(article_params)
      if @author == "true"
        redirect_to root_path
      else
        redirect_to articles_path
      end
    else
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    @author = params[:author]

    if @author == 'true'
      redirect_to root_path
    else
      redirect_to articles_path
    end
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :text, :photo, :photo_small)
    end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def index
    @articles = Article.page(params[:page]).per(5)
    
    respond_to do |format|
      format.html
      format.js {}
    end
  end

  def article
    @article = Article.find(params[:id])
    @count_comments = @article.comments.count
  end

  def about
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  filter_resource_access

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(body: params[:comment][:body], user_id: current_user.id)
    @count_comments = @article.comments.count

    respond_to do |format|
      format.html { redirect_to controller: :blog, action: :article, id: @article.id }
      format.js
    end
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to controller: :blog, action: :article, id: @article.id
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  filter_access_to :all
  
  def index
    @messages = Message.page(params[:page]).per(5)

    respond_to do |format|
      format.html
      format.js {}
    end
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      flash[:success] = "Your message sent."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
 
    redirect_to messages_path
  end

  private
    def message_params
      params.require(:message).permit(:title, :body, :sender)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  filter_resource_access

  def index
    @users = User.page(params[:page]).per(5)

    respond_to do |format|
      format.html
      format.js {}
    end
  end

  def edit
    @user = User.find(params[:id])
    @roles = Role.all
  end

  def update
    @user = User.find(params[:id])
   
    unless @user.update(user_params)
      flash[:error] = "Could not updated user."
    end
    redirect_to users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
 
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:role_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
    when "success"
      "alert-success"   # Green
    when "error"
      "alert-danger"    # Red
    when "alert"
      "alert-warning"   # Yellow
    when "notice"
      "alert-info"      # Blue
    else
      flash_type.to_s
    end
  end

  def find_role_admin
    User.select('users.email, roles.title').joins(:role).where('roles.title = ?', 'admin').first
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="container-fluid"> 
  <div class="row">
    <div class="col-sm-12 col-md-12">

      <div class="page-header">
        <h1>Admin panel</h1>
      </div>
      <div>
        <%= link_to 'Articles', articles_path, class: "btn btn-info" %>
        <%= link_to 'Users', users_path, class: "btn btn-info" %>
        <%= link_to 'Messages', messages_path, class: "btn btn-info" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/_article.html.erb
<tr class="info">
  <td><%= article.id %></td>
  <td>
      <p><%= image_tag(article.photo_small) if article.photo_small? %></p>
      <p class="article_title"><%= link_to article.title, article_path(article) %></p>
  </td>
  <td><%= truncate(strip_tags(article.text), length: 400) %></td>
  <td><%= article.user.name %></td>
  <td><%= article.updated_at %></td>
  <td>
    <%= button_to 'Edit', edit_article_path(article),
            method: :get, class: "btn btn-success btn-xs" %>
  </td>
  <td>
    <%= button_to 'Delete', article_path(article),
          method: :delete,
          data: { confirm: 'Are you sure?' }, 
          class: "btn btn-danger btn-xs" %>
  </td>
</tr>

app/views/articles/_form.html.erb
<%= image_tag(@article.photo) if @article.photo? %></td>

<%= form_for @article, :html => { multipart: true, class: "form-horizontal" } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= hidden_field_tag(:author, @author) %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :title, size: 22, autofocus: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :text, class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_area :text, cols: 40, rows: 30, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :photo, class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :photo %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :photo_small, class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :photo_small %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-4">
      <%= f.submit title_sumbit, class: "btn btn-primary btn-sm"%>
    </div>
  </div>
<% end %>

<div><%= button_to 'Back', articles_path, method: :get, class: "btn btn-default" %></div>

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12">
      <h1>Edit article</h1>

      <%= render partial: 'form', locals: { title_sumbit: 'Save article' } %>
    
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<% provide(:title, 'Articles') %>

<div class="container-fluid"> 
  <div class="row">
    <div class="col-sm-12 col-md-12">

      <div class="page-header">
        <h1>Articles</h1>
      </div>
      <p>
        <%= button_to new_article_path, method: :get, class: 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-plus"></span>
          Add article
        <% end %>
      </p>

      <% if @articles.empty? %>
        <b>No articles</b>
      <% else %>

      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
           <tr class="warning">
              <th>ID</th>
              <th>Article</th>
              <th>Body</th>
              <th>Author</th>
              <th>Updated</th>
              <th colspan="2"></th>
            </tr>
          </thead>
          <tbody id="articles">
            <%= render partial: "article", :collection => @articles, :as => :article %>
          </tbody>
        </table>
        </div>
        <div id="paginator", class="paginate-centre">
          <%= paginate @articles, :remote => true %>
        </div>
      <% end %>

      <p>
        <%= button_to 'Back', admin_path, method: :get, class: "btn btn-default" %>
      </p>

    </div>
  </div>
</div>

app/views/articles/index.js.erb
$('tbody#articles').html('<%= escape_javascript render(partial: "article", :collection => @articles, :as => :article) %>');

$('#paginator').html('<%= escape_javascript(paginate(@articles, :remote => true).to_s) %>');

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12">
    <h1>Create new article</h1>

    <%= render partial: 'form', locals: { title_sumbit: 'Create article' } %>
    
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container"> 
  <div class="col-sm-12 col-md-12">
    <div class="page-header">
      <h1 class="article_title"><%= @article.title %></h1>
    </div>
    <p>
      <%= image_tag(@article.photo) if @article.photo? %>
    </p>
    <p>
      <%= sanitize(@article.text) %>
    </p>

    <h3><%= link_to 'Back', :back %></h3>

  </div>
</div>

app/views/blog/_article.html.erb
<tr>
  <td><%= link_to image_tag(article.photo_small), blog_article_path(article) if article.photo_small? %> </td>
  <td>
    <p class="article_title"><%= link_to article.title, blog_article_path(article) %></p>
    <p><%= truncate(strip_tags(article.text), length: 1000) %></p>

      <div class="article-user">
        <span class="by">by </span><%= article.user.name %>
      </div>

      <div class="article-comment-count">
        <%= pluralize(article.comments.count, 'comment') %>
      </div>
      
    <div>
      <% if permitted_to? :delete, article %>
        <%= link_to edit_article_path(article, params: { author: true }), method: :get, class: 'btn btn-success btn-xs' do %>
            <span class="glyphicon glyphicon-pencil"></span>
            Edit
        <% end %>
        <%= link_to article_path(article, params: { author: true }), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %>
            <span class="glyphicon glyphicon-remove"></span>
            Delete
        <% end %>
      <% end %>
    </div>
  </td>
</tr>

app/views/blog/about.html.erb
<% provide(:about, 'active') %>
<% provide(:title, 'About') %>

<h2>Articles about the hardware and technology</h2>

app/views/blog/article.html.erb
<% provide(:title, @article.title ) %>

<div class="container-fluid"> 
  <div class="row">

    <div class="col-sm-9 col-md-10">

    <div class="container">
      <div class="page-header">
        <h1 class="article_title"><%= @article.title %></h1>
      </div>
      <p class="article-author-date"> by 
        <span class="author"><%= @article.user.name %> </span>
        <%= " on #{l @article.updated_at, :format => :long }" %>
      </p>
      <p>
        <%= image_tag(@article.photo) if @article.photo? %></p>
      <p>
        <%= sanitize(@article.text) %>
      </p>

      <h2 id="count_comment"><%= pluralize(@count_comments, 'Comment') %></h2>
      <div id="comments">
        <%= render @article.comments %>
      </div>


      <h2>Add a comment:</h2>
      <div id="empty-body"></div>
      <%= render 'comments/form' %>

      <%= link_to 'Back', :back, class: "btn btn-default btn-sm" %>
    </div>

  </div>
</div>

app/views/blog/index.html.erb
<% provide(:articles, 'active') %>
<% provide(:title, 'Articles') %>

<div class="container-fluid"> 
  <div class="row">

    <div class="col-sm-12 col-md-12">

    <div class="container">
      <div class="page-header">
        <h2 class="articles-header">Articles</h2>
      </div>

      <% if permitted_to? :new, :articles %>
        <p>
          <%= button_to new_article_path, method: :get, params: { author: true }, class: 'btn btn-primary' do %>
            <span class="glyphicon glyphicon-plus"></span>
            Add article
          <% end %>
        </p>
      <% end %>

      <div class="row">
        <div class="col-sm-12 col-md-12">
          <% if @articles.empty? %>
            <b>No articles</b>
          <% else %>

            <div class="table-responsive">
              <table class="table ">
                <tbody id="articles">
                  <%= render partial: "article", :collection => @articles, :as => :article %>
                </tbody>
              </table>
            </div>
            <div id="paginator", class="paginate-centre"><%= paginate @articles, :remote => true %></div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/blog/index.js.erb
$('tbody#articles').html('<%= escape_javascript render(partial: "article", :collection => @articles, :as => :article) %>');

$('#paginator').html('<%= escape_javascript(paginate(@articles, :remote => true).to_s) %>');

app/views/comments/_comment.html.erb
<div>
  <p>
    <span id="user-comment"><%= comment.user.name %></span>
    <span id="comment-date"> - <%= l comment.updated_at, format: :long %></span>
  </p>
   
  <div class="comments">
    <%= comment.body %>
  </div>

  <p>
    <% if permitted_to? :delete, comment %>
      <%= link_to 'Destroy Comment', [comment.article, comment],
                   method: :delete,
                   data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build], remote: true) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, cols: 70, rows: 5 %>
  </p>
  <p>
    <% if user_signed_in? %>
      <%= f.submit "Create comment", class: "btn btn-primary btn-sm" %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path, class: "btn btn-primary btn-sm" %>
    <% end %>
  </p>
<% end %>

app/views/comments/create.js.erb
<% if @comment.id %>
  $('#empty-body').html('');
  $('#count_comment').html('<%= j pluralize(@count_comments, "Comment") %>');
  $("<%= j render(partial: 'comments/comment', locals: {comment: @comment}) %>").appendTo($("#comments"));
  $('#comment_body').val('');
<% else %>
  $('#empty-body').html('Comment is empty');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> | Hardware and tech</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'shared/navbar' %>

    <div class='main-page-content <%= controller.controller_name %>'>
      <div class="container">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert #{bootstrap_class_for(key)} flash") %>
        <% end %>

        <%= yield %>
      </div>
    </div>

    <footer>
      <p>&copy; Hardware and tech 2016. All Rights Reserved. Developed by <a href="https://github.com/geovo851">Georgy</a></p>
    </footer>

  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message, :html => { multipart: true, class: "form-horizontal" } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :sender, 'Your e-mail*', class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :sender, size: 22, autofocus: true, class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :title, 'Subject*', class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :title, size: 22, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :body, 'Text*', class: "col-sm-1 control-label" %>
    <div class="col-sm-7">
      <%= f.text_area :body, cols: 10, rows: 15, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-4">
      <%= f.submit title_sumbit, class: "btn btn-primary btn-sm"%>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<tr class="info">
  <td><%= message.id %></td>
  <td><%= message.sender %></td>
  <td><%= message.title %></td>
  <td><%= message.body %></td>
  <td><%= message.created_at %></td>
  <td>
    <%= button_to 'Delete', message_path(message),
          method: :delete,
          data: { confirm: 'Are you sure?' }, 
          class: "btn btn-danger btn-xs" %>
  </td>
</tr>

app/views/messages/index.html.erb
<% provide(:title, 'Messages') %>

<div class="container-fluid"> 
  <div class="row">
    <div class="col-sm-12 col-md-12">

      <div class="page-header">
        <h1>Messages</h1>
      </div>

      <% if @messages.empty? %>
        <b>No articles</b>
      <% else %>

      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
           <tr class="warning">
              <th>ID</th>
              <th>Sender</th>
              <th>Subject</th>
              <th>Body</th>
              <th>Created</th>
              <th></th>
            </tr>
          </thead>
          <tbody id="messages">
            <%= render partial: "message", :collection => @messages, :as => :message %>
          </tbody>
        </table>
        </div>
        <div id="paginator", class="paginate-centre">
          <%= paginate @messages, :remote => true %>
        </div>
      <% end %>

      <p>
        <%= button_to 'Back', admin_path, method: :get, class: "btn btn-default" %>
      </p>

    </div>
  </div>
</div>

app/views/messages/index.js.erb
$('tbody#messages').html('<%= escape_javascript render(partial: "message", :collection => @messages, :as => :message) %>');

$('#paginator').html('<%= escape_javascript(paginate(@messages, :remote => true).to_s) %>');

app/views/messages/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12">
    <h2>Contact us:</h2>

    <%= render partial: 'form', locals: { title_sumbit: 'Send' } %>
    
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div> 
        <%= link_to 'Hardware and tech', root_path, id: "logo" %>
      </div>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">
        <li class="<%= yield(:articles) %>"><%= link_to 'Articles', root_path %></li>
        <li class="<%= yield(:about) %>"><%= link_to 'About', blog_about_path %></li>
        <li class="<%= yield(:contact) %>"><%= link_to 'Contact us', blog_contact_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right"> 

        <% if user_signed_in? %>

          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Edit account', edit_user_registration_path %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", destroy_user_session_path,
                            method: "delete" %>
              </li>
            </ul>
          </li>

          <% if permitted_to? :index, :admin %>
            <li><%= link_to 'Admin panel', admin_path %></li>
          <% end %>

        <% else %>

          <li class="<%= yield(:sign_in) %>">
            <%= link_to 'Sign in', new_user_session_path %>
          </li>
          <li class="<%= yield(:sign_up) %>">
            <%= link_to 'Sign up', new_user_registration_path %>
          </li>
           
        <% end %>
       </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_for @user, :html => { multipart: true, class: "form-horizontal" } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.label :name, @user.name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.label :email, @user.email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :category, class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.collection_select(:role_id, @roles, 
                  :id, :title, {:prompt => 'Please select role'}, class: "form-control") %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-4">
      <%= f.submit title_sumbit, class: "btn btn-primary btn-sm"%>
    </div>
  </div>
<% end %>

<div><%= button_to 'Back', users_path, method: :get, class: "btn btn-default" %></div>

app/views/users/_user.html.erb
<tr class="info">
  <td><%= user.id %></td>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.role.title %></td>
  <td><%= user.created_at %></td>
  <td>
    <%= button_to 'Edit role', edit_user_path(user),
            method: :get, class: "btn btn-success btn-xs" %>
  </td>
  <td>
    <%= button_to 'Delete', user_path(user),
          method: :delete,
          data: { confirm: 'Are you sure?' }, 
          class: "btn btn-danger btn-xs" %>
  </td>
</tr>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12">
      <h1>Edit role</h1>

      <%= render partial: 'form', locals: { title_sumbit: 'Save' } %>
    
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>

<div class="container-fluid"> 
  <div class="row">
    <div class="col-sm-12 col-md-12">

      <div class="page-header">
        <h1>Users</h1>
      </div>
      
      <% if @users.empty? %>
        <b>No users</b>
      <% else %>

      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
           <tr class="warning">
              <th>ID</th>
              <th>Name</th>
              <th>Email</th>
              <th>Role</th>
              <th>Created</th>
              <th colspan="2"></th>
            </tr>
          </thead>
          <tbody id="users">
            <%= render partial: "user", :collection => @users, as: :user %>
          </tbody>
        </table>
        </div>
        <div id="paginator", class="paginate-centre">
          <%= paginate @users, :remote => true %>
        </div>
      <% end %>

      <p>
        <%= button_to 'Back', admin_path, method: :get, class: "btn btn-default" %>
      </p>

    </div>
  </div>
</div>

app/views/users/index.js.erb
$('tbody#users').html('<%= escape_javascript render(partial: "user", :collection => @users, :as => :user) %>');

$('#paginator').html('<%= escape_javascript(paginate(@users, :remote => true).to_s) %>');